REV-241: Small fixes for azure support in revizor
Scalr/libcloud pull request #13
Opened 2017-06-13 14:20 UTC by stunko

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-06-16 11:36 UTC, gigimon approved these changes

2017-06-16 12:38 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +NIC_API_VERSION = '2017-03-01'
Может, поменять `api-version` для всех `*nic` методов на эту константу заодно? А то она вроде вынесена, но контролирует далеко не все.

2017-06-21 15:05 UTC, stunko commented on libcloud/compute/drivers/azure_arm.py
> +NIC_API_VERSION = '2017-03-01'
Поменял: 
- NIC_API_VERSION установил в соответствии с https://docs.microsoft.com/en-us/rest/api/network/virtualnetwork/network-interface-cards
- Установил константу NIC_API_VERSION для всех обращений к nic

2017-06-21 15:38 UTC, mermoldy requested changes

2017-06-21 15:38 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +            return False
@decoratorz если blobdriver.get_object начал выбрасывать LibcloudError вместо ObjectDoesNotExistError - значит наш azure_vhd сторадж драйвер тоже сломан https://github.com/Scalr/fatmouse/blob/17f96ab/agent/tasks/storage/azure_vhd.py#L202

@stunko нужно проверить что изменилось и сделать чтобы blobdriver.get_object выбрасывал старую ошибку: ObjectDoesNotExistError

2017-06-21 17:33 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +            return False
@gigimon @stunko поправьте это вливайте в trunk-patched.

@decoratorz после этого мы интегрим trunk-patched в https://scalr-labs.atlassian.net/browse/FAM-986  и выпускаем багфикс в 5.7.5

2017-06-22 06:00 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +            return False
со стораджами все ок, это не аффектит

2017-06-22 06:08 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +            return False
@stunko `_ex_delete_old_vhd` не должен обрабатывать LibcloudError, на нем завязана логика в других местах: https://github.com/Scalr/libcloud/blob/cde503a93/libcloud/compute/drivers/azure_arm.py#L764 , он должен глотать только ObjectDoesNotExistError а все остальное выбрасывать нарерх

2017-06-22 21:26 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +            return False
@mermoldy выдохнули

2017-06-28 12:18 UTC, mermoldy commented on libcloud/common/azure.py
> +API_VERSION = '2015-07-08'
@stunko по умолчанию пусть остается старая версия (чтобы не затрагивать azure classic драйвер), 2015-07-08 нужно переопределить только для AzureBlobsConnection 
 – https://github.com/Scalr/libcloud/blob/a4ad8d4/libcloud/storage/drivers/azure_blobs.py#L158

2017-06-28 13:06 UTC, stunko commented on libcloud/common/azure.py
> +API_VERSION = '2015-07-08'
@mermoldy  Пофиксил

2017-06-28 14:43 UTC, mermoldy approved these changes

2017-06-29 09:50 UTC, decoratorz approved these changes

2017-06-30 12:48 UTC, merged