REV-242 Fix vsphere driver and add list_volumes method
Scalr/libcloud pull request #15
Opened 2017-06-16 13:27 UTC by Theramas

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-06-16 15:45 UTC, uty requested changes

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +    def list_nodes(self, datacenter=None, cluster=None, resource_pool=None):
имена тех параметров, которых нет в аналогичном методе `base.NodeDriver` класса, должны начинаться с `ex_*`.

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +        return disks
```python
nodes = [node] if node else self.list_nodes()
volumes = []

for node in nodes:
    volumes.extend([self._to_volume(disk) for disk in node.extra['disks'])

return volumes
```

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +                    raise
```python
if 'Could not find a VM with path' not in e.message:
    raise
```

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +        # id = uuid
нужно удалить

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +        if ip_address and not ":" in ip_address:
`and ":" not in ip_address:`

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +                if not ":" in ip_address:
`if ":" not in ip_address:`

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +                if not ":" in ip_address:
хотя лучше убрать `not` и под `if` поставить одно `continue` с комментом почему IPv6 адреса полностью скипаются.

2017-06-16 15:45 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +                             state='active',
почему `state` всегда `'active'`?

2017-06-16 15:45 UTC, uty commented on libcloud/utils/networking.py
> +            raise
так нельзя делать, получается невалидный айпи — это публичный айпи. В конкретных местах, где нужно съедать эту ошибку нужно ставить `try: except:` но не в общей утилите для _всего_ libcloud.

2017-06-19 14:25 UTC, Theramas commented on libcloud/compute/drivers/vsphere.py
> +                             state='active',
Потому что у объектов, которые отдает pysphere, state вообще нет. И у вмвари диски не могут существовать отдельно от инстанса, насколько я знаю. А либкладный класс какое-то состояние требует. Самое логичное тут active, т.к. если диск существует, то существует и сервер.

2017-06-19 14:40 UTC, uty commented on libcloud/compute/drivers/vsphere.py
> +                             state='active',
http://pubs.vmware.com/horizonmirage-44/index.jsp#com.vmware.horizonmirage.admin.doc/GUID-C9E8D468-DDBF-4296-9942-3AC119886CA8.html
А про что здесь пишут, это никак не получить? Если точно нет, то `state` тогда вообще не нужно задавать, пусть будет дефолтный `UNKNOWN`.

2017-06-20 09:44 UTC, uty approved these changes

2017-06-20 10:18 UTC, mermoldy requested changes

2017-06-20 10:18 UTC, mermoldy commented on libcloud/compute/drivers/vsphere.py
> +                if 'Could not find a VM with path' not in e.message:
Exception.message - депрекейтед с python 2.6
`if 'Could not find a VM with path' not in str(e)`

2017-06-20 10:18 UTC, mermoldy commented on libcloud/compute/drivers/vsphere.py
> +        vm_paths = self.connection.client.get_registered_vms(datacenter=ex_datacenter,
максимальная длинна строки - 79 символов
http://libcloud.readthedocs.io/en/latest/development.html#code-style-guide

2017-06-20 10:40 UTC, mermoldy approved these changes

2017-06-23 20:23 UTC, merged