FAM-1029 Handle AWS RequestLimitExceeded via exponential backoff
Scalr/libcloud pull request #17
Opened 2017-07-19 14:34 UTC by mermoldy

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-07-25 18:09 UTC, maratkomarov requested changes

2017-07-25 18:09 UTC, maratkomarov commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@mermoldy 👎 новому аргументу. 

Нужно расширять возможности агрумента backoff. Вместо константы, это может быть еще и генератор. Чтобы вписать юзкейс с `5s .. 1m` мы передаем что-то вроде `itertools.chain((5, 10, 20, 40), itertools.repeat(60))`, и хендлим такое расширение в единственном месте в `def retry()`.

2017-07-26 10:04 UTC, mermoldy commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@maratkomarov убрал, в backoff будет передаваться `iterable`, последовательность будет генеиться так: `cycle_last((retry_delay * i for i in backoff))`, т.е. для `5s .. 1m` параметры будут: `retry_delay=5`, `backoff=(1, 2, 4, 8, 12)`

2017-07-26 10:23 UTC, uty commented on libcloud/utils/misc.py
> +    for _ in itertools.repeat(0):
`while True:` ?

2017-07-26 10:23 UTC, uty commented on libcloud/utils/misc.py
> +            )
лучше вернуть как было с обычным `if`. От тернарных выражений на пять строчек только хуже становится.

2017-07-26 10:23 UTC, uty commented on libcloud/utils/misc.py
> +def cycle_last(iterable):
нужен докстринг и имя лучше пусть будет по аналогии с `itertools.repeat()` — `repeat_last()`

2017-07-26 10:23 UTC, uty commented on libcloud/test/common/test_retry_limit.py
> +        connection = Connection(
наверное, нужен тест и для `backoff` заданного итерируемым объектом.

2017-07-26 10:23 UTC, uty commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@maratkomarov, @mermoldy, по-моему, сложновато. Почему бы не сделать возможность `retry_delay` задавать итерируемым объектом с конкретными значениями задержки?

2017-07-26 10:50 UTC, mermoldy commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@uty для наглядности можно так `retry_delay=1, backoff=(5, 10, 20, 40, 60)`, `backoff` изначально предназначен как коэффициент для роста прогрессии, поэтому использовать его логичнее

2017-07-26 11:27 UTC, uty commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@mermoldy, по-моему, `backoff` был добавлен как простой и непродуманный способ управления задержкой. Его влияние выглядит как вообще взятое с потолка — с чего бы `backoff` возведенный в _степень_ номера повтора был определен как хороший коэффициент? Его значения >4 вообще смысла не имеют.

Понятно, что можно передавать как ты написал. Только тогда если код выше решит по-человечески хранить список задержек, то он никогда не будет использовать `backoff` как _коэффициенты_, а как буквально `retry_delay`.

2017-07-26 11:47 UTC, mermoldy commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@uty backoff изначально делался только чтобы добавить экспоненциальный повтор – https://issues.apache.org/jira/browse/LIBCLOUD-360

2017-07-26 12:05 UTC, uty commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@mermoldy, хорошо, не полностью с потолка, а криво скопирован со swiftclient :) Но проблемы это не отменяет.

2017-07-26 12:29 UTC, mermoldy commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@uty можно переделать на `retry_delay`, но `backoff` тогда нужно выпиливать совсем, смысла в нем не будет если в `retry_delay` будет передаваться готовая последовательность
cc @maratkomarov

2017-07-26 12:32 UTC, uty commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@mermoldy, я тоже так бы хотел сделать, но не уверен что это примут. Человек, который реквестил LIBCLOUD-360 наверняка использует `backoff` до сих пор, как и возможно многие другие.

2017-07-26 17:28 UTC, maratkomarov commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@mermoldy сходил по ссылке, и теперь поддерживаю @uty в роли для `retry_delay`. Мы не сможем выпилить backoff не поломав чужой код, но можем выключить из игры -  засетить `backoff=1`

2017-07-27 09:47 UTC, mermoldy commented on libcloud/utils/misc.py
> +DEFAULT_DELAY_LIMIT = 320
@maratkomarov @uty переделал на `retry_delay`

2017-07-27 15:18 UTC, uty requested changes

2017-07-27 15:18 UTC, uty commented on libcloud/utils/misc.py
> +          retry_exceptions=None):
Не стоит менять порядок аргументов без надобности.

2017-07-27 15:18 UTC, uty commented on libcloud/utils/misc.py
> +            retry_msg = "Server returned %r, retry request in %s seconds ..."
`"retrying"`

UPD: даже `"retrying for"`, т.к. это про общее время для всех попыток

2017-07-27 15:18 UTC, uty commented on libcloud/utils/misc.py
> +                delay * (backoff ** i) for i, delay in enumerate(retry_delays)
Нужно вообще игнорировать `backoff` при `retry_delay` заданным набором. Легко ли навскидку посчитать, какие задержки будут при таких параметрах? `retry(retry_delay=(1, 2, 5, 10, 30), backoff=3)` Насколько очевидно поведение из описания `backoff`: `multiplier added to delay between attempts.`?

2017-07-27 15:18 UTC, uty commented on libcloud/utils/misc.py
> +                        raise
Теперь тут такая ситуация, что мы можем "поспать" 30 секунд, при оставшемся таймауте в 5, а потом просто выкинуть исключение. Раньше хотя бы при просроченном таймауте совершалась финальная попытка запроса.
Нужно высчитывать `sleep()` так, чтобы он был не превышал таймаут и в любом случае выполнять последний запрос.

2017-07-27 23:01 UTC, mermoldy commented on libcloud/utils/misc.py
> +                        raise
@uty поправил по замечаниям

2017-07-28 09:21 UTC, uty approved these changes
Одна минипоправка, остальное lgtm

2017-07-28 09:21 UTC, uty commented on libcloud/utils/misc.py
> +                        "in %s seconds ..."
Сорри, я просмотрел где это сообщение используется, "for" таки не нужен.

2017-07-28 09:21 UTC, uty commented on libcloud/utils/misc.py
> +                        return retry_loop(*args, **kwargs)
Странновато, что таймаут отодвигается по `RateLimitReachedError`, но так было и в исходном коде. @maratkomarov, что ты скажешь?

2017-07-28 15:50 UTC, decoratorz requested changes

2017-07-28 15:50 UTC, decoratorz commented on libcloud/utils/misc.py
> +def repeat_last(iterable):
@mermoldy В функции неправильно обрабатывается edge-case c пустым iterable. Для получения первого элемента надо делать `next` и пропагейтить StopIteration если iterable пустой. 

Так же этот кейс неправильно обрабатывается в коде на уровень выше. retry_delay в виде пустого списка вызовет Exception когда сюда: https://github.com/Scalr/libcloud/pull/17/files#diff-b18a9d271b9ef1e6bee1c97e93086c12R389 придет None. После этого фикса запрос вообще ни разу не выполнится.

Надо задаунгрейдить тип retry_delay до collection.Seqeuence и добавить проверку на len(retry_delay) > 0 тут: https://github.com/Scalr/libcloud/pull/17/files#diff-67ac44ca403f0e5f950198c5f072b043R533 и тут: https://github.com/Scalr/libcloud/pull/17/files#diff-b18a9d271b9ef1e6bee1c97e93086c12R370

2017-07-28 17:00 UTC, mermoldy commented on libcloud/utils/misc.py
> +def repeat_last(iterable):
@decoratorz починил

2017-07-28 17:06 UTC, decoratorz approved these changes

2017-07-29 00:12 UTC, maratkomarov approved these changes

2017-07-29 00:12 UTC, merged