SCALRCORE-7790 add methods for upgrading cluster's master node
Scalr/libcloud pull request #27
Opened 2018-03-15 14:58 UTC by vaniakov

2018-03-26 09:54 UTC, uty requested changes

2018-03-26 09:54 UTC, uty commented on libcloud/container/drivers/gke.py
> +        """
@vaniakov, докстринги в других методах оформлены по-другому, лучше сделать так же.

2018-03-26 09:54 UTC, uty commented on libcloud/container/drivers/gke.py
> +        :param zone: zone name.
@vaniakov, `Cluster compute zone name`

2018-03-26 09:54 UTC, uty commented on libcloud/container/drivers/gke.py
> +        :param zone: Cluster compute zone.
@vaniakov, `zone` параметр должен называться `ex_zone` и аналогично другим методам должен по дефолту быть `None` т.к. есть `self.zone`

2018-03-26 11:51 UTC, vaniakov commented
@uty уніфікував стиль докстрінгів

2018-03-26 13:25 UTC, uty commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
тут тоже нужен `or '-'`

2018-03-26 13:27 UTC, vaniakov commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
@uty потрібен. Якщо `ex_zone` i `self.zone` == `None` - повертаємо список всіх кластерів незалежно від регіону. Для цього треба запит `/zones/-/clusters/`.

2018-03-26 13:29 UTC, vaniakov commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
@uty цей endpoint не приймає `-` як зону.

2018-03-26 13:36 UTC, uty commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
тогда стоит кидать осмысленное исключение, если `self.zone` и `ex_zone` == `None`

2018-03-26 13:45 UTC, vaniakov commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
@uty ніде в gke немає exception якщо ex_zone=None. В результаті такого запиту виникне змістовинй exception `InvalidRequestError: 'location "None" does not exist.'`

2018-03-26 13:52 UTC, uty commented on libcloud/container/drivers/gke.py
> +            ex_zone = self.zone
@vaniakov, а если есть с таким названием? :)
Ну и проще это здесь определить, чем делать заведомо ошибочный реквест.

2018-03-26 14:17 UTC, uty approved these changes

2018-03-29 22:47 UTC, maratkomarov approved these changes

2018-05-03 00:03 UTC, merged