Feature/scalrcore 8898
Scalr/libcloud pull request #31
Opened 2018-05-22 14:29 UTC by vpyvovarov

## Add BigQuery client

### Description

BQ client is required for implementing billing for GCE. 

After discussions were decided put this code under new category `extra`. This was done because BQ doesn't fit to any other (computer, storage DNS and etc). 

To not reinvent the weel we use existing lib from google. 

There are two client - one general client for BQ, second for getting billing data from BQ. I know that they are not following general code style of `libcloud`.  `libcloud` was designed for providing a similar interface for all cloud providers. But BQ is a service that hardly has any analog from other cloud providers. So the main goal of putting this code under `libcloud`, is having one place for all client used at Scalr.

### Status
ready for review

### Code snipets 
```from libcloud.extra.types import Provider
from libcloud.extra.providers import get_driver

creds = {'account_id': 'hosted-scalr@scalr-labs.iam.gserviceaccount.com',
 'client_email': 'hosted-scalr@scalr-labs.iam.gserviceaccount.com',
 'cloud': 'gce',
 'cloud_credentials_id': '1c5f17a81359',
 'env_id': 10,
 'private_key': '-----BEGIN PRIVATE KEY-----\n'
                'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKvLE46Z6N9lUr\n'
                '9RfeVTO3B0dv04Qe3r2aIjzSYB8xyLEsC5goieGWfFchCkvim+7+4E7iKXM4Ly4a\n'
                'sdFja0Ra/6uXs9Ad6QB2yYONQMph3QrFDVsLYYAYrkIOE2soI2mj9YmWxthVcVwH\n'
                'vNeA/HedMlfzXnOjnf8wNcVFPURPfGdmXBTb9w2AkrZGchggpjS2nYR19bvQma3v\n'
                '26JYiDQNK1tJ8gdkbnS11p6WSY7Vv21cqExEcwfexW096ePPOgrgAlKttbfQpkcr\n'
                '9IoNu8Nk5ccN6qWJpJ/SlueEDuwum2HJyFWQn++bDECd44fOnJg7j924AXP698EQ\n'
                '0GRuyzjJAgMBAAECggEAR/xyZFprx7NaLC3HDbjd1Yk0WuTAOBhQ/unm7y2q4fUF\n'
                'YRo/AEHSyHeJ6f3itBk+4AbZR2ZEf5GTdYxwXgqpdCIXEebeBLcCY6BZ3vAQUskT\n'
                'rn0okXYstiGs6orO3gvJ46YilxZj56mjG+yzUR0un2Ug14lZrTrsz0IHMs8AY9Eg\n'
                'Z8o/LSF1Jv7arQkNtLklhjxW7BJNNVHtroG8u7scuMACw4mTVLrOd4S4bFJvaln2\n'
                'EAkEHvjpjE6z7XrRwgxhwFGVSgkYqw4vnPyu/jgb7gEwOqfoeElLfJk5lLTQTDyG\n'
                'fkVwlq8xrcPKuaehIYSC4kQ+lRbvvC9OXISmc/Z+FQKBgQC/raIRt4wV7mnXFDzM\n'
                'nbrSE/HXWXno2GixybyjAUYUVOWsrbwk8H43ZRMVHbGCG98//raj7dIMPa5PfCad\n'
                'PNi1QFdRJAIgbDldV6hF5z/lIrqswSBvWBAEz7NU3FYPwgKmuCjIaHmn0+23O0UL\n'
                '45IVzNp2A1ug5FgqCLN9XiqFawKBgQC5SxRYO1oQW7UWyTSW2Uzj2S8gcwcDSA7f\n'
                'y0Yc2SkNHlAXAEYvMbIjFZzN5y2jnCavJ6v9TYyo/UmdRRp/L4Zl14h0PAdzjnEn\n'
                'geQPP+nohrZzLDqbu+ZZfFhjYq1T4By768tE8cRGMIy1r5nRcEWr4o2egG1yR+74\n'
                'yb2lrVCTmwKBgA4VJLYmhR1LYe1SaFEkOYibvIX05fcMh0ygpMJZIpv1zNYOAae5\n'
                'H5zUST2g69zCTXm3LhYHMAqEMZ1XYsLkqItQidnFSn61VNWdzhgssE4Wah6tJcPo\n'
                'dWzVEbjnY09PEsDLAPwQaPfCo1F2AlGoS6BcZ6SKBJ5iiHO2JfHNDFS3AoGAJqer\n'
                'Dt0S5Oa82IwRFIcwqzfbxQE6LU0TDUzyy4HiNoJkYugDvES5zOftVmcr9j3VNCUq\n'
                'lCVher+cY9rOtEnN1+Em7li3lTvaD0vhr+y9d2zjExPfBi4k1/ZA2jrzvdO7Ktj+\n'
                'BtwI/juSnzSK+k5ZuooA0VgpfPXUvMIZdj652JECgYEAtC2Ih4XIK5G8bfr7MKG0\n'
                'GS3IMqD2Zs3LWAJozXR/4MmXTUelnxO7Ow7Oic24Ho5sPwJS9yYxdBSoSB40S/+l\n'
                'rtuEUE/5UW/qlCd9fDz2oygwlrPDyEhs1C1H2mfphYIKLqnU8T3HdMGCwkSIGiVb\n'
                'LWKaMX/sshd9UkqOcMjyED0=\n'
                '-----END PRIVATE KEY-----\n',
 'project_id': 'scalr-labs',
 'proxy': None,
 'token_uri': 'https://accounts.google.com/o/oauth2/token'}

bqb = get_driver(Provider.GOOGLE_BQ_BILLING)
bqb = bqb(creds)

query = """SELECT
   FORMAT_TIMESTAMP("%Y-%m-%d %H", usage_start_time) as dtime,
   service.description as service,
   sku.description as sku,
   project.name as project_name,
   export_time,
   usage_start_time,
   usage_end_time,
   cost * currency_conversion_rate as cost
  FROM `billing.gcp_billing_export_v1_00D54C_776AB2_C6075D`
  WHERE export_time >= "2018-01-01 00:00:00" and cost != 0
  ORDER BY dtime"""

res = bqb.execute(query)

for i in res:
    print(i)
```

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)

2018-05-22 22:30 UTC, maratkomarov requested changes

2018-05-22 22:30 UTC, maratkomarov commented on libcloud/extra/drivers/google.py
> +from google.api_core.exceptions import NotFound
@vpyvovarov Нет. Мы используем libcloud как универсальный клиент к любому API любого клауда. Заместо  зоопарка из десятка API клиентов с конфликтующими зависимостями. В libcloud.common.google есть все необходимые строительные блоки для работы с любым API гугла.

2018-05-22 22:50 UTC, uty commented on libcloud/extra/drivers/google.py
> +from google.api_core.exceptions import NotFound
@maratkomarov, also, take a look at my comment https://scalr-labs.atlassian.net/browse/SCALRCORE-8898?focusedCommentId=138127&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-138127

2018-05-23 12:29 UTC, vpyvovarov commented on libcloud/extra/drivers/google.py
> +from google.api_core.exceptions import NotFound
що вирішили? Ми все ще пихаємо цю штуку в libcloud але запість гугблівського клієнта працєюмо через API?

2018-05-23 22:26 UTC, maratkomarov commented on libcloud/extra/drivers/google.py
> +from google.api_core.exceptions import NotFound
@vpyvovarov Да, добавляем в libcloud. Обсуждаем в тикете.

2018-05-25 18:37 UTC, maratkomarov requested changes

2018-05-25 18:37 UTC, maratkomarov commented on libcloud/big_data/drivers/google.py
> +class BigQueryBilling(BigQuery):
@vpyvovarov работа с конкретным датасетом - не скоуп libcloud. Это будет в costmgr в gcp биллинге.

2018-05-25 18:37 UTC, maratkomarov commented on libcloud/big_data/drivers/google.py
> +from libcloud.common.base import BaseDriver
@vpyvovarov по обсуждению в тикете - нет смыла делать абстракцию big data. Имплементим конкретные драйвера  под каждое API, при этом поставляя из через драйвер фабрику в общем стиле libcloud

```python
from libloud.extra import get_driver, Provider

cls = get_driver(Provider.GOOGLE_BQ)
bq = cls(*args, **kwargs)  # interface same as Google Compute Driver

```

2018-05-31 12:47 UTC, naviot requested changes

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google.py
> +    responseCls = GoogleResponse
@vpyvovarov навіщо ти перегрузив host і responseCls якщо в базовому класі ті ж самі значення?

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google.py
> +        self.request_path = '/bigquery/%s/projects/%s' % (API_VERSION, project)
@vpyvovarov з коду випливає що project обовязковий елемент kwargs
можливо є сенс тоді додати окремим параметром в інтерфейс конструктора?
або якось показати що він required

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google.py
> +    def list_datasets(self):
@vpyvovarov докстрінги  у всі публічні методи

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +def _millis_from_datetime(value):
@vpyvovarov навіщо ці методи _millis_from_datetime, _microseconds_from, _datetime _millis? 
вони  ніде не використовується

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +DEFAULT_TASK_COMPLETION_TIMEOUT = 180
@vpyvovarov  для чого дефолт?

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +    else:
@vpyvovarov можна без else блоку

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +        return value.lower() in ['t', 'true', '1']
@vpyvovarov достатньо ['true', '1'] ?
**'t'** ⊆ **'true'**

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +    return datetime.datetime.strptime(value, '%Y-%m-%d').date()
@vpyvovarov по загальному стилю формат '%Y-%m-%d' також потрібно в константи

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +    if isinstance(result, six.binary_type):
@vpyvovarov нам потрібен Py2 compatible код?

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +    def __init__(self, name, field_type, mode='NULLABLE',
@vpyvovarov думаю варто додати силку на опис схеми https://cloud.google.com/bigquery/docs/schemas
так буде зрозуміліше звідки кінці ростуть

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +    def from_api_repr(cls, api_repr):
@vpyvovarov чого це не в конструкторі?
які ще можливі варіанти ініціалізації?

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +_CELLDATA_FROM_JSON = {
@vpyvovarov мб варто якийсь дефол додати щоб потім банально keyerror не виліз

2018-05-31 12:47 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +
@vpyvovarov лишня пуста строчка чи заготовка під докстрінгу :slightly_smiling_face: ?

2018-05-31 12:54 UTC, naviot commented on libcloud/extra/providers.py
> +                                module=module, klass=klass)
@vpyvovarov no newline at end of file

2018-05-31 12:58 UTC, naviot reviewed
@vpyvovarov і ліцензію краще вліпити у всі файли, мб ми захочемо це пропихнути в апстрім

2018-06-01 09:06 UTC, vpyvovarov commented on libcloud/extra/drivers/google.py
> +    responseCls = GoogleResponse
+

2018-06-01 09:06 UTC, vpyvovarov commented on libcloud/extra/drivers/google.py
> +        self.request_path = '/bigquery/%s/projects/%s' % (API_VERSION, project)
Подивися як цей клас інстанціюється https://github.com/Scalr/libcloud/blob/trunk/libcloud/common/base.py#L975
`project` вкидається в `kwargs` через `_ex_connection_class_kwargs`
Якщо `project` буде відсутній то райзнеться ексепшн.

2018-06-01 09:06 UTC, vpyvovarov commented on libcloud/extra/drivers/google.py
> +    def list_datasets(self):
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +def _millis_from_datetime(value):
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +    else:
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +        return value.lower() in ['t', 'true', '1']
```
>>> 't' in ['t', 'true', '1']
True
>>> 't' in ['true', '1']
False
```
Можливо я не зрозумів питання.

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +    return datetime.datetime.strptime(value, '%Y-%m-%d').date()
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +    if isinstance(result, six.binary_type):
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +    def __init__(self, name, field_type, mode='NULLABLE',
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +    def from_api_repr(cls, api_repr):
done

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/drivers/google_bq_utils.py
> +_CELLDATA_FROM_JSON = {
Що буде в  дефолті?

2018-06-01 09:07 UTC, vpyvovarov commented on libcloud/extra/providers.py
> +                                module=module, klass=klass)
done

2018-06-01 09:54 UTC, naviot commented on libcloud/extra/drivers/google.py
> +        self.request_path = '/bigquery/%s/projects/%s' % (API_VERSION, project)
@vpyvovarov ok

2018-06-01 09:54 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +        return value.lower() in ['t', 'true', '1']
@vpyvovarov я помилився
``` 
>>> 't' in ['true', '1']
False
>>> 't' in 'true'
True
```

2018-06-01 09:54 UTC, naviot commented on libcloud/extra/drivers/google_bq_utils.py
> +_CELLDATA_FROM_JSON = {
@vpyvovarov якась заглушка або ще варіант райзити окремий тип мопилки якщо ключа не знайшлось
а хендлити це вже в коді який буде використовувати сам драйвер

2018-06-01 11:10 UTC, naviot approved these changes

2018-07-02 09:14 UTC, vpyvovarov commented
Бренч під цей ПР відколотий з некоректної гілки. Мала б бути `trunk-patched` a не `trunk`. Зробив новий ПР https://github.com/Scalr/libcloud/pull/34 з `trunk-patched`. Цей закриваю.

2018-07-02 09:14 UTC, closed without merging