SCALRCORE-8911 Add support of Rate Card API and Usage Aggregates API  to libcloud
Scalr/libcloud pull request #32
Opened 2018-05-22 15:11 UTC by joker-ace

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2018-05-22 16:17 UTC, uty requested changes

2018-05-22 16:17 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                      usage_api_version='2015-06-01-preview'):
Метод называется UsageAggregates здесь должен называться соответствующе: `ex_get_usage_aggregates`.
Параметры так же: `reported_start_time`, `reported_end_time` и тп. Иначе нужно по коду библиотеки лишний раз лазить и разбираться что куда попадает.

2018-05-22 16:17 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            'showDetails': 'true',
Почему нет параметра для `showDetails`?

2018-05-22 16:17 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                break
Раз возвращается итератор, нужно это как-то отметить в названии метода. Например, вместо `*_get_*` поставить `*_iterate_*`

2018-05-23 08:40 UTC, joker-ace commented on libcloud/compute/drivers/azure_arm.py
> +                break
@uty поправил

2018-05-23 10:25 UTC, uty requested changes

2018-05-23 10:25 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            'reportedStartTime': reported_start_time.strftime('%Y-%m-%dT%H:%S:%M+00:00'),
Секунды и минуты перепутаны.

2018-05-24 11:35 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            'reportedStartTime': reported_start_time.strftime('%Y-%m-%dT%H:%S:%M+00:00'),
@levsh, были перепутаны и здесь https://github.com/Scalr/int-scalr/blob/master/app/python/scalrpy/util/analytics.py#L1482

2018-05-24 11:37 UTC, uty approved these changes

2018-05-24 14:59 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +            r = self.connection.request(action, params=params)
@joker-ace у меня тут сомнения. Запрос каждый раз делается с одними и теми же params(за исключением continuationToken). А что будет если в next_link придут другие параметры?

2018-05-28 14:57 UTC, levsh requested changes

2018-05-28 14:57 UTC, levsh commented on libcloud/test/compute/test_azure_arm.py
> +        ratecard = self.driver.ex_get_rate_card('0026P')
@joker-ace нужен тест на ex_iterate_usage_aggregates с не пустым nextLink

2018-05-29 15:31 UTC, levsh approved these changes

2018-07-09 12:56 UTC, merged