SCALARIZR-8989 Libcloud > Vmware driver deficiencies
Scalr/libcloud pull request #33
Opened 2018-06-08 12:00 UTC by mermoldy

2018-06-18 16:24 UTC, maratkomarov requested changes
@mermoldy @uty Если у сабтаска есть собственный PR, он не может идти сразу в master (тут trunk-patched).  PR нужно направлять в ветку парент тикета.

2018-06-18 16:24 UTC, maratkomarov commented on libcloud/compute/drivers/vmware.py
> +    def _content(self):
@uty если это каждый раз API колл под капотом, то стоит переделать в метод и внимательно пересмотреть чтобы он не дублировался внутри приватных метод коллов при вызове публичного метода.

2018-06-18 16:24 UTC, maratkomarov commented on libcloud/compute/drivers/vmware.py
> +    def _content(self):
сори, @mermoldy

2018-06-19 12:05 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +    def _content(self):
@maratkomarov поправил `_content` и сменил base бранч на родительский тикет

2018-06-19 12:08 UTC, maratkomarov approved these changes

2018-06-19 12:09 UTC, maratkomarov commented
@uty глянь ты

2018-06-20 11:27 UTC, uty requested changes

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +            node.extra['create_time'] = creation_dates.get(node.id)
У большинства libcloud объектов есть поле `created_at`

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        ] if node is not None else self._list_virtual_machines()
Такие длинные тернарные операторы лучше раскладывать на обычные `if: else:`
```python
if node is None:
    virtual_machines = self._list_virtual_machines()
else:
    virtual_machines = [self.ex_get_vm(node)]
```

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +    def _query_nodes_creation_dates(self, virtual_machine=None):
Может, лучше `_query_node_creation_times()`? Т.к. параметр эвента называется `createdTime` и "date" — это все же больше про день/месяц/год, а не про точное время.

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +            for event in created_events}
Что такое `VmRegisteredEvent`? Разве он тоже исключает другие?

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +                    creation_dates[device_id] = event.createdTime
Этот алгоритм не очень сходится с SCALRCORE-9050. На VMware правда никак нельзя получить время создания файла-диска? Без затрагивания эвентов vm.

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        Recursively walks the specified folder.
Нужно дописать что-нибудь про возвращаемые данные.

2018-06-20 11:27 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        history_collector.SetCollectorPageSize(1000)
Размер страницы в тикете про пейджинацию я выношу в константу так https://github.com/Scalr/libcloud/blob/feature/SCALRCORE-8984/libcloud/compute/drivers/gce.py#L43 . Тут тоже стоит.

2018-06-20 15:33 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +            for event in created_events}
@uty ``VmRegisteredEvent`` обычно тригерится после ``VmCreatedEvent``, но может быть вызван и сам по себе при импорте существующей виртуальной машины (из .vmx файла). Детальной информации по этому в доках нет.

2018-06-20 15:33 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +                    creation_dates[device_id] = event.createdTime
@uty Подогнал алгоритм под шаред-диски, кроме ивентов дату создания вольюмов никак не получить.

2018-06-20 15:34 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +                    creation_dates[device_id] = event.createdTime
@uty По остальным замечаниям тоже внес правки.

2018-06-20 15:40 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +            for event in created_events}
@mermoldy, понятно, окей

2018-06-20 15:44 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        Recursively walks the specified folder and return a list of all sub-folders found.
Возвращаются же элементы, из folder и всех sub-folders, а не сами sub-folders.

2018-06-20 15:44 UTC, uty approved these changes

2018-06-20 15:48 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        Recursively walks the specified folder and return a list of all sub-folders found.
@uty fixed

2018-06-22 08:21 UTC, merged