SCALRCORE-9049 Libcloud > Implement pagination for VMware using Property Collector
Scalr/libcloud pull request #39
Opened 2018-06-26 14:30 UTC by mermoldy

2018-07-09 11:07 UTC, uty requested changes

2018-07-09 11:07 UTC, uty commented on libcloud/utils/networking.py
> +    return address.count('.') == 3
`return is_valid_ip_address(address) and address.count('.') == 3` же.

2018-07-09 11:07 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +            raise Exception("Too broad type of the file query")
Наверное, стоит рейзить `LibcloudException`

2018-07-09 11:07 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        Wait for a vCenter task to finish.
Что насчет `pyVim.task.WaitForTask`?
https://github.com/vmware/pyvmomi/blob/31d9ac5f4b19cd883383490ca696f9150f442c4e/pyVim/task.py#L88
https://github.com/vmware/pyvmomi-community-samples/blob/39bd95553df337ae35f1b101c487b37063967555/samples/snapshot_operations.py#L142

2018-07-09 11:07 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +                yield node
Тут все же нужно возвращать именно список, иначе нарушается контракт `page()`. В других `result_to_*()` то же самое.

2018-07-09 11:07 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        virtual_machine = self.ex_get_vm(node) if node is not None else None
Тут нужно конструировать две `request_fn()` функции, а не выполнять запросы сразу. И возвращать разные типы плохо — у генератора нет `page()`.

2018-07-09 12:35 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        virtual_machine = self.ex_get_vm(node) if node is not None else None
@uty Доставать `create_times` нужно одним запросом перед паджинацией, потому что они будут нужны полностью для сопоставления таймштампов на уже первой странице vmdk файлов.

2018-07-09 12:35 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +                yield node
@uty поправил

2018-07-09 12:38 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        Wait for a vCenter task to finish.
@uty `pyVim.task.WaitForTask` инициализирует много лишних ресурсов, свой `wait_for_task` получился заметно быстрее.

2018-07-11 10:08 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +        if not LibcloudError(file_query, vim.FileQuery):
Опечатка

2018-07-11 10:10 UTC, uty commented on libcloud/compute/drivers/vmware.py
> +            begin_time=datetime.now() - timedelta(days=30)
А откуда эти 30? Нужно хотяб комментом пояснить

2018-07-11 10:24 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        if not LibcloudError(file_query, vim.FileQuery):
@uty неудачно копипастом промазал, поправил

2018-07-11 10:25 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +            begin_time=datetime.now() - timedelta(days=30)
@uty вынес в константу с комметном

2018-07-11 10:32 UTC, uty approved these changes

2018-07-11 10:46 UTC, merged