SCALRCORE-8984 Libcloud > list_* methods should return all available objects
Scalr/libcloud pull request #40
Opened 2018-06-26 15:18 UTC by uty

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2018-06-27 11:44 UTC, mermoldy requested changes

2018-06-27 11:44 UTC, mermoldy commented on libcloud/utils/misc.py
> +    def set_page_size(self):
Сеттеры – не сеттеры, думаю лучше будет ``update_page_size``, ``update_next_page_token`` и ``next_page_token`` – либо ``get_``, либо проперти.

2018-06-27 11:44 UTC, mermoldy commented on libcloud/utils/misc.py
> +        self.fn_kwargs = fn_kwargs
``fn_args``/``fn_kwargs`` – ``request_args``/``request_kwargs`` – иначе не понятно к чьим ``kwargs`` идет обращения в наследниках.
``split_fn`` – ``post_request_fn`` или ``process_response_fn``, тоже не ясно что за сплит.

2018-06-27 11:44 UTC, mermoldy commented on libcloud/compute/drivers/gce.py
> +        return list(self.iterate_images(*args, **kwargs))
В некоторых list методах ``ex_page_size`` обнуляется, нужно сделать консистентное поведение.

2018-06-27 11:44 UTC, mermoldy commented on libcloud/compute/drivers/gce.py
> +            self._ex_populate_volume_dict()
[_ex_populate_volume_dict](https://github.com/Scalr/libcloud/blob/e15d3a1/libcloud/compute/drivers/gce.py#L7765) не нужно вызывать для каждой страницы.

2018-06-27 11:44 UTC, mermoldy commented on libcloud/compute/drivers/gce.py
> +    def iterate_nodes(self, ex_zone=None, ex_use_disk_cache=True, ex_page_size=DEFAULT_PAGE_SIZE):
Почему не ``ex_iterate`` нейминг как в GCE драйвере?

2018-06-27 11:44 UTC, mermoldy commented on libcloud/compute/drivers/gce.py
> +        def nodes_splitter(response):
Во многих методах сплиттеры получаются большие, возможно стоит выносить их в отдельные методы и стандартизовать нейминг:
- ``list_<entity>``
- ``(ex_?)iterate_<entity>``
- ``_response_to_<entities>``

2018-06-27 11:44 UTC, mermoldy commented on libcloud/utils/misc.py
> +class PageList(object):
Пагинатор получился сильно заточен под RestAPI, в vmware используется SOAP и будет сложно натянуть одно на другое, думаю стоит выделить пагинатор в отдельный интерфейс и реализовать RestPageList (текущий PageList), чтобы остальные драйверы смогли заимплементить свою логику пагинации при необходимости.

2018-06-27 11:51 UTC, uty commented on libcloud/compute/drivers/gce.py
> +        return list(self.iterate_images(*args, **kwargs))
@mermoldy, это сделано специально, т.к. `ec2` может вернуть вообще все и без пейджинации. Тогда как другие клауды неявно ее всегда имеют. Поэтому, на ec2 сбрасывается пейджинация в `list_*`

2018-06-27 11:55 UTC, mermoldy commented on libcloud/compute/drivers/gce.py
> +        return list(self.iterate_images(*args, **kwargs))
@uty ок, понятно

2018-06-27 12:02 UTC, uty commented on libcloud/compute/drivers/gce.py
> +        def nodes_splitter(response):
Ну он и так стандартизован: `*list*` заменяется на `*iterate*` — так получается нейминг для paging методов. `*_splitter` — так для преобразователей response в список элементов. Но насчет последнего можно подумать про переименование.
Выносить мне не очень нравится, т.к. алгоритм становится менее понятным и иногда нужны замыкания.

2018-06-27 12:03 UTC, uty commented on libcloud/compute/drivers/gce.py
> +    def iterate_nodes(self, ex_zone=None, ex_use_disk_cache=True, ex_page_size=DEFAULT_PAGE_SIZE):
Этот коммент и так к gce.py... Тут только один `ex_iterate_snapshots()`, т.к. оригинальный метод называется `ex_list_snapshots()`

2018-06-27 12:05 UTC, uty commented on libcloud/utils/misc.py
> +class PageList(object):
Тут поподробней опиши, что именно тяжело натянуть, и если есть примеры vmware пейджинации, то тоже добавь.

2018-06-27 13:44 UTC, mermoldy commented on libcloud/utils/misc.py
> +class PageList(object):
@uty Разные типы объектов паджинируются по разному, PropertyCollector который делается сейчас в принципе работает похожим образом (использует токен):
```
options = vmodl.query.PropertyCollector.RetrieveOptions(
    maxObjects=10  # page size
)

result = []
# first page
properties = collector.RetrievePropertiesEx([filter_spec], options)
result.extend(properties.objects)

while properties.token:
    # other pages
    properties = collector.ContinueRetrievePropertiesEx(
        token=properties.token)
    result.extend(properties.objects)
```
но list_fn разный для первой страницы и остальных, с разными сигнатурами.

Ещё есть паджинация для выборки тасков/ивентов (пока что используется только для внутренних методов):
```
content = self._retrieve_content()
history_collector = content.eventManager.CreateCollectorForEvents(
    filter_spec)  # type: vim.event.EventHistoryCollector
history_collector.SetCollectorPageSize(DEFAULT_PAGE_SIZE)
history_collector.ResetCollector()

events = history_collector.latestPage
while events:
    for event in events:
        yield event
    events = history_collector.ReadPreviousEvents(DEFAULT_PAGE_SIZE)
```
здесь совсем нет токенов.

Во обеих случаях большинство кода в PageList излишне, в наследниках для VMware будет проще переопределить базовую реализацию чем натянуть её на логику текущего PageList, поэтому можно выделить интерфейс с не заимплеменченными page/has_more/iter и использовать его если это удобнее.

2018-06-27 13:53 UTC, mermoldy commented on libcloud/compute/drivers/ec2.py
> +        node_paginator.apply(extend_adresses, scope='page')
@uty Почему не сделать extend_address сразу в сплиттере?

2018-06-29 14:56 UTC, uty commented on libcloud/compute/drivers/gce.py
> +            self._ex_populate_volume_dict()
@mermoldy, если этого не делать, то в этом дикте данные могут устареть между вызовами страниц. Плюс, сброс `self._ex_volume_dict = {}` некуда вставить.

2018-06-29 15:03 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +        node_paginator.apply(extend_adresses, scope='page')
да, стоит там. Просто этот метод был написан первым, я тогда еще думал над ответственностью сплиттера — он мог возвращать raw элементы респонза. Но потом понял, что в этом нет смысла

2018-06-29 16:08 UTC, uty commented on libcloud/utils/misc.py
> +    def set_page_size(self):
@mermoldy, долго думал над неймингом здесь и понял, что это алгоритм нужно немного поменять. `update_*` нейминг тоже путал, т.к. функции обновляют параметры реквеста, а не просто page_size/page_token

2018-06-29 16:57 UTC, mermoldy approved these changes

2018-07-02 10:20 UTC, mermoldy commented on libcloud/utils/misc.py
> +    def next_page_token(self):
@uty 
> [pylint] E0202:An attribute defined in libcloud.utils.misc line 460 hides this method

2018-07-02 10:23 UTC, uty commented on libcloud/utils/misc.py
> +    def next_page_token(self):
@mermoldy, спасибо, забыл этот класс поправить

2018-07-04 10:24 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> -
@uty почему выброшен кусок функционала?

2018-07-04 10:24 UTC, maratkomarov commented on libcloud/utils/misc.py
> +class PageList(object):
@uty Сережа подметил правильные юзкейсы. PageList очень сложно расширять. Помимо этого весь код libcloud перелопачен, из него выкинуты некоторые вещи работающие для кого-то раньше. Нам нужно сконструировать решение кторое можно было бы легче  встроить в существующую кодовую базу.

Давайте думать в сторону интерфейса:
 - Пейджер должен уметь извлекать данные из очередного response для доступа к следующей странице.
 - Пейджер должен сообщить что больше страниц нет.

```python
class Paginator(Generator):
    def __init__(self, *args, **kwargs):
        """Construct paginator.
        *args, **kwargs - what was passed to iter_<something> method."""
        pass

    def __iter__(self) -> NextToken:
        """returns NextToken data required by uplevel code to construct request 
        to access next page, or raises StopIteration.
        """
        pass

    def send(self, response, items=None):
        """Receives from uplevel code response object, and prepares data for Next Token.
        """
        pass

class NextToken(dict):
    token: str

# Usage

iter_something(*args, **kwargs):
    pager = paginator(*args, **kwargs)
    while next_token in pager:
        # morph request with next token data
        # do request
        # parse response items
        pager.send(response, items)
        yield from data

# Paginator as simple generator function

def paginator(*args, **kwargs):
    yield NextToken()
    while True:
        response, items = yield
        # prepare Next
        if not having next:
            return
        yield NextToken(token=nexttoken)
```

2018-07-04 10:26 UTC, maratkomarov requested changes
Дизайн Paginator-а.

2018-07-04 10:27 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> -
@maratkomarov, это не функционал, это параметры для deprecated способа листинга имейджей через офферы, паблишеры, sku.

2018-07-04 10:28 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> -
@uty ок

2018-07-04 11:06 UTC, uty commented on libcloud/utils/misc.py
> +class PageList(object):
@maratkomarov, мы уже давно голосом обсудили и договорились насчет интерфейса.
Кроме пары мест, где использовалось что-то deprecated, весь функционал остался неизменным, и встроился он очень легко. Не знаю, куда еще легче.

Интерфейс `PageList` был взят из существовавшего [GCEList](https://github.com/Scalr/libcloud/pull/40/files/e52c02992834ef5ae0d91e07b289ef64fc1da0d9#diff-a5605647c310d2daf7050000a8134212L209), который был доработан для общего случая. Суть заключается в том, что он умеет доставать NextToken из респонза, подставлять его в следующий и запрашивать страницы, пока они не закончатся. Я не вижу, где это не применимо или сложнорасширяемо.
В vmware уже используется https://github.com/Scalr/libcloud/pull/39/files#diff-d71bd62f5a1c54041299cec7d6fde602R66

В твоем предложении я вообще интерфейса не вижу. Если вся суть идеи сводится к определению NextToken и передаче его вызывающему коду, то с этим справится обычная функция. Тогда каждый `iterate_*()` метод нужно будет переписать на `while:` + `for:`, от чего избавиться — основная суть вынесения пейджинатора в класс была.

P.S.: Мне вообще жутко не нравятся эти вывернутые итераторы `while True: something = yield`, которые у нас стали вдруг везде появляться. Они только больше "спагеттифицируют" алгоритм, необычным образом разбивая его на куски. Пока разберешься в том что они делают... Почему бы не использовать привычные классы для хранения состояния?

2018-07-04 11:47 UTC, maratkomarov commented on libcloud/utils/misc.py
> +class PageList(object):
@uty хорошо, будь по твоему. я сейчас бегло пробегусь по коду.

2018-07-04 11:49 UTC, maratkomarov requested changes

2018-07-04 11:49 UTC, maratkomarov commented on libcloud/extra/drivers/google.py
> +            for row in query_job.rows:
@uty yield from query_job.rows

2018-07-04 11:49 UTC, maratkomarov commented on libcloud/utils/misc.py
> +                yield item
@uty yield from self.page()

2018-07-04 11:49 UTC, maratkomarov commented on libcloud/utils/misc.py
> +        while self.has_more():
@uty has_more - это raise StopIteration

2018-07-04 12:55 UTC, uty commented on libcloud/extra/drivers/google.py
> +            for row in query_job.rows:
@maratkomarov, это код из SCALRCORE-8898. Я не пойму, почему он тут в diff отображается, когда `trunk-patched` я в base (feature/SCALRCORE-9010) ветку подмерджил.

2018-07-04 13:52 UTC, uty commented on libcloud/utils/misc.py
> +        while self.has_more():
`has_more()` может использоваться внешним кодом, если страницы отдельно запрашиваются. Поэтому тут заменить на выбрасывание `StopIteration` не выйдет.

2018-07-04 13:52 UTC, uty commented on libcloud/utils/misc.py
> +                yield item
Заменил

2018-07-04 13:56 UTC, mermoldy commented on libcloud/utils/misc.py
> +                yield item
@maratkomarov @uty libcloud поддерживает python начиная с 2.5, ``yield from`` появился в 3.3

2018-07-04 14:44 UTC, maratkomarov commented on libcloud/utils/misc.py
> +                yield item
@uty значит отменяем.

2018-07-04 14:44 UTC, uty commented on libcloud/utils/misc.py
> +                yield item
Вернул :)

2018-07-04 14:44 UTC, maratkomarov commented on libcloud/utils/misc.py
> +        while self.has_more():
@uty ok

2018-07-04 16:05 UTC, maratkomarov approved these changes

2018-07-09 11:05 UTC, merged