SCALRCORE-9265 (libcloud) Cost manager > Azure > Enterprise Billing
Scalr/libcloud pull request #49
Opened 2018-08-13 14:17 UTC by pydevd

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2018-08-14 08:45 UTC, levsh requested changes

2018-08-14 08:45 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +    def ex_iterate_usage_details(self, usage_start_date, usage_end_date, api_version='2018-06-30'):
@pydevd есть тикет SCALRCORE-9010. Там решалась такая же проблема(AzurePageList). Нужно чекнуть и найти общий знаменатель, чтобы не было двух вариантов решения одной и той же задачи.

2018-08-14 08:45 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +    def ex_iterate_usage_details(self, usage_start_date, usage_end_date, api_version='2018-06-30'):
@pydevd я так понимаю интерфейс должен быть
```
CONSUMPTION_API_VERSION = '2018-06-30'
ex_iterate_usage_details(self,
    billing_period=None,
    start_date=None, 
    end_datе=None,
    api_version=CONSUMPTION_API_VERSION):
    ...
```
И внутри выполняться логика из таблицы https://docs.microsoft.com/en-us/rest/api/consumption/#working-with-billing-periods-and-date-ranges

2018-08-20 09:02 UTC, levsh approved these changes

2018-08-20 09:02 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +            filter_str += "properties/usageEnd lt '%s'" % end_date.strftime("%Y-%m-%d")
@pydevd такие вещи удобно делать через формирование списка условий и их объединения потом нужным условным оператором
```
conditions = []
if A:
    conditions.append('a > 0')
if B:
    conditions.append('b > 0')
filter = ' AND '.join(conditions)
```

2018-09-04 22:35 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +            filter_str += "properties/usageEnd lt '%s'" % end_date.strftime("%Y-%m-%d")
@pydevd зря проигнорил

2018-09-14 18:16 UTC, merged