FAM-690 Add support for disks on Azure
Scalr/libcloud pull request #5
Opened 2017-02-20 15:34 UTC by mermoldy

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-03-10 23:59 UTC, maratkomarov requested changes

2017-03-10 23:59 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +                    break
@mermoldy raise, если не нашли свободный LUN

2017-03-10 23:59 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +    def ex_list_nics(self, ex_resource_group=None):
@mermoldy я так понимаю по libcloud соглашениям ex_ приставляется только к extra параметрам основных методов, а параметры extra методов идут без префикса.

2017-03-10 23:59 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +            raise LibcloudError((
@mermoldy посмотри, в примерах у azure детач сделан элегантнее https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py#L158

2017-03-10 23:59 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +        provisioning_state = properties.get('provisioningState', '').lower()
@mermoldy почему бы приведение state не сделать картой.

2017-03-10 23:59 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +    def ex_delete_resource(self, resource):
@mermoldy другие методы в качестве ресурса могут принимать basestring

2017-03-13 10:19 UTC, mermoldy commented
@maratkomarov пофиксил

2017-03-14 09:13 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +                    "uri": _get_instance_vhd()
@mermoldy поясни, пожалуйста, в чем преимущество выноса кода get_instance_vhd в отдельную функцию и вызов его каждый раз? Раньше этот код выполнялся всего однажды и дальше использовалась переменная instance_vhd, а теперь он выполняется два раза

2017-03-14 09:13 UTC, levsh commented on libcloud/compute/drivers/azure_arm.py
> +        if ex_resource_group is None:
@mermoldy и тут не могу сообразить. Зачем мы даем пользователю возможность передать дефолтное значение None(используя kwarg вместо arg), а потом проверяем на None и рейзим ValueError. И по коду ниже тоже часто встречается.

2017-03-14 09:24 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +                    "uri": _get_instance_vhd()
@levsh instance_vhd не нужен когда создается managed osDisk(ex_use_managed_disks) c AzureImage

2017-03-14 09:38 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +        if ex_resource_group is None:
@levsh у NodeDriver есть базовый интерфейс - https://github.com/apache/libcloud/blob/6395d62/libcloud/compute/base.py#L1011 , расширяется он только опциональными параметрами (ex_*), args - будет нарушать интерфейс, это общий подход в libcloud

2017-03-24 16:21 UTC, maratkomarov approved these changes

2017-03-24 16:22 UTC, merged

2017-03-24 16:23 UTC, maratkomarov commented
todo: contribute into upstream