SCALRCORE-10476 Cost Manager > VMWare listing optimization
Scalr/libcloud pull request #57
Opened 2018-11-06 11:22 UTC by mermoldy

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2018-11-06 20:57 UTC, maratkomarov requested changes

2018-11-06 20:57 UTC, maratkomarov commented on libcloud/compute/drivers/vmware.py
> +        return name in self._cache if self._allow_caching else False
@mermoldy где инвалидация кеша? один инстанс драйвера за время не насосет память?

2018-11-06 21:42 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        return name in self._cache if self._allow_caching else False
@maratkomarov Пока что данные кэшируются один раз и навсегда, если делать универсальный механизм то нужно кэшировать словарь `creation_times` с датой последнего запроса, и при последующих вызовах `_query_*_creation_times` запрашивать данные относительно этой даты, тогда кэш будет постоянно обновляться и понадобится инвалидация.
Но для кейса костменеджера это не нужно, данные кэшируются сразу после инициализации драйвера (`ex_pre_caching`) и дальше будут только использоваться list-методами.

2018-11-06 22:25 UTC, maratkomarov commented on libcloud/compute/drivers/vmware.py
> +        return name in self._cache if self._allow_caching else False
@mermoldy ok

2018-11-07 10:16 UTC, levsh requested changes
Для фикса в 7.11 ок, но для мастер я бы тут еще подумал. Кэш должен быть более гранулированный и управляемый. Как пример, клиенту может быть нужно время создания виртуальных машин, но не дисков. Сейчас ex_pre_caching вытянет для всех.

2018-11-07 10:16 UTC, levsh commented on libcloud/compute/drivers/vmware.py
> +            begin_time=datetime.now(timezone.utc) - timedelta(days=self._created_at_limit),
@mermoldy тут точно не будет проблем с зонами и utc? Может лучше datetime.utcnow? Есть вариант проверить?

2018-11-07 10:16 UTC, levsh commented on libcloud/compute/drivers/vmware.py
> +        if not virtual_machine and self._has_cache('node_creation_times'):
@mermoldy получается если хотим значение для конкретной vm, то кэшем воспользоваться не получится?

2018-11-07 10:46 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +            begin_time=datetime.now(timezone.utc) - timedelta(days=self._created_at_limit),
@levsh тестил этот момент – вроде бы все ок, c `datetime.utcnow` работает неправильно, похоже что вмварь парсит дату без `tzinfo` как локальное время.
```
In [13]: str(datetime.utcnow())
Out[13]: '2018-11-07 10:37:36.375588'

In [14]: str(datetime.now(timezone.utc))
Out[14]: '2018-11-07 10:37:38.296152+00:00'
```

2018-11-07 11:52 UTC, mermoldy commented on libcloud/compute/drivers/vmware.py
> +        if not virtual_machine and self._has_cache('node_creation_times'):
@levsh Поправил, кэш возвращается всегда, записывается только если был вызов листинга по всем вм/датацентрам.

2018-11-08 08:13 UTC, levsh approved these changes

2018-11-12 18:40 UTC, maratkomarov approved these changes

2018-11-13 19:45 UTC, merged