(libcloud) SCALRCORE-10491 Agent > Bump Azure ARM API version to 2018-04-01
Scalr/libcloud pull request #58
Opened 2018-11-13 14:08 UTC by uty

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2018-11-13 22:27 UTC, maratkomarov approved these changes

2018-12-18 15:30 UTC, sbelyakov commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
@uty как вы заполняете в данный момент эту пропертю?

2018-12-18 15:32 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
@sbelyakov, `accountType`? В новом АПИ ее нет, поэтому никак.

2018-12-18 15:35 UTC, sbelyakov commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
@uty из того что я понял, то вы убрали поле в запросе. И ажур теперь не получает это поле и по дефолту создает только HDD диски. А есть 3 возможных варианта дисков... Посмотри плиз там должно быть поле sku->name. У нас в рест апи так есть. Надо по другому тело запроса формировать

2018-12-18 15:43 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
@sbelyakov, я понял, поправлю. Покажи как у вас в коде это делается

2018-12-18 15:48 UTC, sbelyakov commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
@uty пока никак, но я над этим работаю. вместо accountType у нас будет новое поле sku, а в нём поле name и туда будет записываться тип. https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate#request-body

2018-12-18 15:49 UTC, sbelyakov commented on libcloud/compute/drivers/azure_arm.py
> -                      ex_resource_group=None, ex_account_type=None,
у вас вероятно просто поле sku
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-manage-disks#attach-disk-to-existing-vm

2018-12-20 12:29 UTC, mermoldy requested changes

2018-12-20 12:29 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +                      ex_sku=None, ex_resource_group=None,
@uty ``ex_sku_name`` - в ``sku`` объекта могут быть и другие поля - https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate#disksku

2018-12-20 13:08 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                      ex_sku=None, ex_resource_group=None,
@mermoldy, согласен, поменял

2018-12-20 13:08 UTC, mermoldy approved these changes

2019-01-03 19:23 UTC, merged