SCALRCORE-12174 (FAM) Libcloud update azure_arm driver from upstream/trunk
Scalr/libcloud pull request #66
Opened 2019-04-02 09:10 UTC by danikmil

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2019-04-02 11:45 UTC, mermoldy requested changes

2019-04-02 11:45 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +    def list_images(self, location=None, ex_publisher=None, ex_offer=None,
@danikmil Это сломает `cloud inventory` в cost-manager'е, он использует iterate_* методы драйверов для ленивой пагинации по ресурсам, нужно дописать поддержку нужных параметров в ``iterate_images``.

iterate_* методы это наша фича - SCALRCORE-8984

2019-04-02 11:54 UTC, danikmil commented on libcloud/compute/drivers/azure_arm.py
> +    def list_images(self, location=None, ex_publisher=None, ex_offer=None,
@mermoldy  ок, переробляю.

2019-04-02 15:14 UTC, danikmil commented on libcloud/compute/drivers/azure_arm.py
> +    def list_images(self, location=None, ex_publisher=None, ex_offer=None,
@mermoldy Добавив новий метод з апстриму для get_image з назвою `list_vm_images`, щоб можна було робити виборку для image_id типу `CoreOS:CoreOS:Stable:latest` і при тому не зломати існуючий функціонал для `iterate_images`.

2019-04-02 15:56 UTC, mermoldy approved these changes

2019-04-03 11:48 UTC, gigimon approved these changes

2019-04-10 23:27 UTC, merged