FAM-791 Add Modify Storage method to Libcloud for EC2
Scalr/libcloud pull request #7
Opened 2017-03-29 14:59 UTC by uty

## Added support of next EC2 API methods: ModifyVolume and DescribeVolumesModifications 

### Description

tbd

### Status

- work in progress

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-03-31 19:51 UTC, maratkomarov commented
@uty  у меня будет времени все это внимательно посмотреть, я гляну после @mermoldy и @decoratorz

2017-03-31 20:12 UTC, uty commented
Я еще не все привел по стилю, требуемому либклаудом, так что эти моменты можно пропускать

2017-04-06 20:24 UTC, mermoldy commented on libcloud/compute/drivers/ec2.py
> +class EC2VolumeModification(object):
@uty если это не ec2 специфичная фича то нужно добавить `VolumeModification` и унаследоваться от него
и `__repr__` здесь не помешает

2017-04-06 20:24 UTC, mermoldy commented on libcloud/compute/drivers/ec2.py
> +        self.modification_state = modification_state
@uty  `modification_state` можно задефайнить аналогично
https://github.com/apache/libcloud/blob/cb2fc66/libcloud/compute/types.py#L290
https://github.com/apache/libcloud/blob/cb2fc66/libcloud/compute/drivers/ec2.py#L3138
чтобы использовать в агенте только общие константы

2017-04-06 20:59 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +class EC2VolumeModification(object):
Это класс-контейнер для ответа на специфические запросы к AWS API — начальное состояние модификации, при вызове `ex_modify_volume()` и промежуточные при поллинге через `ex_describe_volumes_modifications()`. На GCE нет поллинга, а ответ на аналог `ex_modify_volume()` практически не похож по структуре, поэтому базовый класс толком и не выделить.

Про `__repr__()` — согласен.

2017-04-06 21:00 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +        self.modification_state = modification_state
Да, ты прав.

2017-04-10 09:47 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +        self.modification_state = modification_state
On the second thought, я не уверен что это нужно, по причинам описанным в другом ответе. Например, в аналогичном классе не объявлены никакие константы для состояния https://github.com/apache/libcloud/blob/cb2fc66/libcloud/compute/drivers/ec2.py#L2829

2017-04-10 11:36 UTC, mermoldy commented on libcloud/compute/drivers/ec2.py
> +        self.modification_state = modification_state
@uty если не делать базовый класс для `EC2VolumeModification` то согласен, выносить нет смысла
и судя по всему `EC2VolumeModification` должен называться `ExEC2VolumeModification`

2017-04-10 11:54 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +        self.modification_state = modification_state
Я на секунду тоже так подумал, но почему-то только `ExEC2AvailabilityZone` назван в таком стиле. Другие `ex_*` методы если возвращают объекты, то классы этих объектов названы просто с `EC2*`. https://github.com/apache/libcloud/blob/cb2fc66/libcloud/compute/drivers/ec2.py#L2838

2017-04-14 14:58 UTC, decoratorz requested changes

2017-04-14 14:58 UTC, decoratorz commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
@uty А нужно ли это вообще? Больше нигде в коде libcloud не нашел использования этого параметра, хотя многие методы aws его поддерживают, например подобный `DescribeVolumes`. Сделаем консистентно с ним: выпилив next_token и max_results аргументы (во втором без поддержки первого мало смысла).

2017-04-14 22:47 UTC, maratkomarov commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
@uty @decoratorz значит ли это что libcloud не поддерживает пейджинг при листинге вольюмов?

2017-04-18 09:58 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
@maratkomarov, @decoratorz, да, не поддерживает. И с этим связана одна неприятная вещь: https://github.com/Scalr/fatmouse/blob/master/common/utils/libcloudutil.py#L33 . Из-за того, что каждый ответ логгируется, один-два запроса на список вольюмов на нашем HS полностью забивают `scalarizr_debug.log` и он ротейтится.

2017-04-19 00:33 UTC, maratkomarov commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
@uty А где мы делаем DescribeVolumes без конкретного volume-id или instance-id ?

2017-04-19 07:44 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
@maratkomarov, да везде https://github.com/Scalr/fatmouse/blob/master/common/utils/libcloudutil.py#L127
https://github.com/Scalr/fatmouse/blob/master/agent/tasks/storage/base.py#L700
Фильтрация происходит на нашей стороне.

2017-04-20 01:10 UTC, maratkomarov commented on libcloud/compute/drivers/ec2.py
> +            raise NotImplementedError(
Продолжим в https://scalr-labs.atlassian.net/browse/FAM-848

2017-04-20 01:15 UTC, maratkomarov approved these changes

2017-04-21 09:04 UTC, decoratorz approved these changes

2017-04-21 21:01 UTC, merged