FAM-902 Add support for storage containers and unmanaged disks in libcloud
Scalr/libcloud pull request #8
Opened 2017-05-12 14:19 UTC by mermoldy

## Changes Title (replace this with a logical title for your changes)

### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-05-23 20:23 UTC, decoratorz approved these changes

2017-05-23 20:51 UTC, maratkomarov commented
@uty твой апрув

2017-05-24 12:13 UTC, uty requested changes

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            is_vhd_exists = self._ex_is_vhd_exists(
`vhd_exists` и `_ex_vhd_exists()`

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                'name': 'unmanaged-vol-{}'.format(str(uuid.uuid4())[0:8]),
Что если кто-то захочет задавать `name` сам?

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            id, params={"api-version": RESOURCE_API_VERSION})
Чуть выше в `ex_get_nic()` версия апи задается прямо cтрокой и отличается от той, которая в константе `RESOURCE_API_VERSION`. Ты проверял что так работает? Т.к. я сделал как в `ex_get_nic()`; нужно поправить кому-то из нас.

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +            blob. (optional)
"unmanaged"

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
Почему без передачи `ex_vhd_resource_group` не должно работать? В `self._ex_is_vhd_exists()` проводится поиск VHD в переданной Resource Group, тогда отсутствие `ex_vhd_resource_group` может считаться `is_vhd_exists = False`, разве нет?

2017-05-24 12:13 UTC, uty commented on libcloud/compute/drivers/ec2.py
> +    def list_volumes(self, node=None, ex_volume_ids=None):
А, так ты полностью изменения из https://github.com/Scalr/libcloud/pull/9 перенес, тогда тот нужно будет закрыть.

2017-05-24 12:21 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
@uty ресурсгруппа нужна не для поиска объекта а для получения ключей от нужного сторадж аккаунта

2017-05-24 12:46 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
Да, но ключи в свою очередь нужны только для поиска объекта же. В этой функции `ex_vhd_resource_group` больше ни для чего не используется.

2017-05-24 13:30 UTC, mermoldy commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
@uty я сначала неправильно понял

> тогда отсутствие ex_vhd_resource_group может считаться is_vhd_exists = False
но если диск все таки существует тогда будет ошибка при аттаче, `attach_volume` должен либо правильно определять `createOption`, либо пользователь должен сам явно его задавать

2017-05-24 15:52 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
Меня на самом деле это и смущает. Обычно методы драйвера совсем "тупые", просто преобразовывают данные в одном формате в другой и выполняют один соответствуюзий запрос. А этот метод больше ответственности берет на себя, и даже если пользователь уверен в своих действиях ему никак лишнего запроса не избежать.

Думаю, что лучше вынести `creationOption` параметром. Это нормально получать ошибку аттача в случае чего.

Давай спросим у @maratkomarov третье мнение.

2017-05-24 16:12 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
@mermoldy @uty  `creationOption` нужно выносить параметром, а `ex_vhd_resource_group` убирать.  Создайте тикет на это. Сейчас уже слишком поздно что менять.

@uty на будущее, твой аппрув должен стоять до @decoratorz и до тестинга.

2017-05-24 16:12 UTC, maratkomarov commented on libcloud/compute/drivers/azure_arm.py
> +            id, params={"api-version": RESOURCE_API_VERSION})
@decoratorz разобрались?

2017-05-24 16:14 UTC, decoratorz commented on libcloud/compute/drivers/azure_arm.py
> +            id, params={"api-version": RESOURCE_API_VERSION})
@maratkomarov Да, смержим этот пул реквест, тут уже есть код @uty.

2017-05-24 16:40 UTC, uty commented on libcloud/compute/drivers/azure_arm.py
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
@maratkomarov, для этого нужно переводить тикет в джире на код ревью и ассайнить его на ревьюера. Или хотя бы реквестить ревью _после_ того, как код был написан.

2017-05-24 16:42 UTC, maratkomarov commented
Второе было. Первое будем улучшать.

On Wed, May 24, 2017, 09:40 Gennadiy Stas <notifications@github.com> wrote:

> *@uty* commented on this pull request.
> ------------------------------
>
> In libcloud/compute/drivers/azure_arm.py
> <https://github.com/Scalr/libcloud/pull/8#discussion_r118303705>:
>
> > @@ -913,14 +923,29 @@ def attach_volume(self, node, volume, ex_lun=None, **ex_kwargs):
>              else:
>                  raise LibcloudError("No LUN available to attach new disk.")
>
> -        disks.append({
> -            'lun': ex_lun,
> -            'createOption': 'attach',
> -            'managedDisk': {
> -                'id': volume.id
>
>
> -            }
> -        })
> +        if ex_vhd_uri is not None:
> +            if ex_vhd_resource_group is None:
> +                raise AttributeError(
> +                    "'ex_vhd_resource_group' of the VHD blob is not specified.")
>
> @maratkomarov <https://github.com/maratkomarov>, для этого нужно
> переводить тикет в джире на код ревью и ассайнить его на ревьюера. Или хотя
> бы реквестить ревью *после* того, как код был написан.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Scalr/libcloud/pull/8#discussion_r118303705>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA9ToSCVeT1o8M4Bwgfp0qcd4-4hDHXYks5r9F2NgaJpZM4NZWSP>
> .
>

2017-06-02 03:27 UTC, maratkomarov approved these changes

2017-06-02 09:48 UTC, uty approved these changes

2017-06-02 16:44 UTC, merged